version: "3.9"
networks:
  leantime:
    external: false
volumes:
  mysql:
services:
  leantime-dev:
    build: .
    ports:
      - "8080:8080"
    volumes:
     - "../:/var/www/html"
    networks:
      - leantime
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=leantime
      - MYSQL_USER=leantime
      - MYSQL_PASSWORD=leantime
      - MYSQL_DATABASE=leantime
    networks:
      - leantime
    volumes:
      - mysql:/var/lib/mysql:rw
