name: Acceptance tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version

    - name: Build with Maven
      run: mvn -B clean test

    - name: Run Acceptance Tests
      run: |
        make Acceptance-test-ci
