name: Acceptance tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
     
    steps:
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          brew install colima
          colima delete
          colima start
      
      - uses: actions/checkout@v3

      - name: Run Acceptance Tests
        run: |
          make Acceptance-test
