name: Acceptance tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17

        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: browser-actions/setup-firefox@v1
      - run: firefox --version

      - name: Run Unit Tests
        run: |
          make unit-test

      - name: Run Acceptance Tests
        run: |
          make acceptance-test-ci
