name: Changelog CI

on:
  workflow_dispatch:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: version
        run: echo "version=$(make get-version)" >> $GITHUB_OUTPUT
        id: version
        
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ steps.version.outputs.version }}
          config_file: .github/workflows/changelogConfig.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
