name: Static Analysis

on:
  pull_request:
    branches: [ "master" ]

jobs:
  phpstan:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: make build-dev

    - name: Run Tests
      run: make phpstan
